site_name: Fab Foundation Poland
repo_name: judycurie/ffp
site_url: https://www.fabfoundation.pl/
copyright: Fab Foundation Poland

nav:
    - Home: index.md
    - About:
      - nav/about/mission.md
      - nav/about/people.md
      - nav/about/regulations.md


    - Research:
      - nav/research/areas.md
      - nav/research/international-scientific-council.md
      - nav/resources.md
    - Fab Institute: nav/fablabs/fab-institute.md
    - Events: nav/events.md

    - Donate:
      - nav/donate/donate.md
      - nav/donate/tax-deductions.md
    - Contact: nav/contact.md

theme:
  name: simple-blog
  custom_dir: template
  title_style: normal
  favicon: assets/ffp-logo-white.svg
  logo: assets/ffp-icon.jpg
  # theme_style: light
  colors:
    text: black
    title: black
    primary: black
    background: white
plugins:
  - gallery:
      examples_dirs: docs/examples          # path to your example scripts
      gallery_dirs: docs/generated/gallery  # where to save generated gallery
      # ... (other options)

  - search  # make sure the search plugin is still enabled
markdown_extensions:
    - def_list
    - pymdownx.tasklist:
        custom_checkbox: true
