site_name: Fab Foundation Poland
repo_name: FernandoCelmer/mkdocs-simple-blog
repo_url: https://github.com/FernandoCelmer/mkdocs-simple-blog
site_url: https://www.fernandocelmer.com/
copyright: Judy Curie

nav:
    - Home: index.md
    - About: nav/about.md
    - Projects:
      - nav/setup/components.md
      - nav/setup/colors.md
      - nav/setup/fonts.md
      - nav/setup/logo.md
      - nav/setup/favicon.md
    - Development:
      - nav/development/development-guide.md
      - nav/development/release-notes.md

theme:
  name: simple-blog
  favicon: assets/favicon.ico
  logo: assets/230125_Logo1.jpg
  theme_style: light
  site_name_style: normal
  title_style: bold
  colors:
    text: black
    title: black
    primary: black
    background: white
  components:
    site_name: true
    title: true
    menu: true
    preview: true
    footer: true
