site_name: Fab Foundation Poland
site_url: https://www.fernandocelmer.com/
copyright: Judy Curie

nav:
    - Home: index.md
    - About: nav/about.md
    - Contact: nav/contact.md
    - Donate: nav/donate.md

theme:
  name: simple-blog
  favicon: assets/ffp-logo-white.svg
  logo: assets/ffp-icon.jpg
  theme_style: light
  site_name_style: normal
  title_style: bold
  colors:
    text: black
    title: black
    primary: black
    background: white
  components:
    site_name: true
    title: true
    menu: true
    preview: true
    footer: true
